name: sentiment-nlp
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - nltk=3.8.1
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pip
  - pip:
      - fastapi==0.110.0
      - uvicorn==0.29.0
      - joblib==1.3.2
      - kaggle==1.5.12
